# Generated by Django 4.1.1 on 2022-11-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_rename__date_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_name',
            field=models.TextField(null=True),
        ),
    ]
